### ISSUE TITLE
파일업로드 유효성 검사 로직

### ISSUE THREAD

**Issue by youyeul301** [receiptAutoScan/receipt-frontend#12]
## Description:
파일업로드 유효성 검사 로직
## To-Do:
- [x] 파일 업로드 API 분리
- [x] 파일 업로드 유효성 검사 로직 구현
- [x] 파일 업로드 기능 작동 확인
