### ISSUE TITLE
업로드 된 매출 기록 조회기능 구현

### ISSUE THREAD

**Issue by youyeul301** [receiptAutoScan/receipt-frontend#15]
## Description:
업로드 된 매출 기록 조회기능 구현
## To-Do:
- [ ] 일별 조회 API 생성
- [ ] 월별 조회 API 생성
- [ ] 년별 조회 API 생성
- [ ] API 호출 및 조회 기능 구현
